# Economy table: code -> (M2 ticker, FX symbol or None for USD, currency)
# FX convention: FX_IDC:<CCY>USD and FX:EURUSD/GBPUSD all quote USD-per-local -> MULTIPLY.
ECON = {
    "US": ("ECONOMICS:USM2", None,             "USD"),
    "CN": ("ECONOMICS:CNM2", "FX_IDC:CNYUSD",  "CNY"),
    "EZ": ("ECONOMICS:EUM2", "FX:EURUSD",      "EUR"),
    "JP": ("ECONOMICS:JPM2", "FX_IDC:JPYUSD",  "JPY"),
    "GB": ("ECONOMICS:GBM2", "FX:GBPUSD",      "GBP"),
    "KR": ("ECONOMICS:KRM2", "FX_IDC:KRWUSD",  "KRW"),
    "CA": ("ECONOMICS:CAM2", "FX_IDC:CADUSD",  "CAD"),
    "AU": ("ECONOMICS:AUM3", "FX_IDC:AUDUSD",  "AUD"),  # Australia: broad money M3
    "CH": ("ECONOMICS:CHM2", "FX_IDC:CHFUSD",  "CHF"),
    "IN": ("ECONOMICS:INM2", "FX_IDC:INRUSD",  "INR"),
    "TW": ("ECONOMICS:TWM2", "FX_IDC:TWDUSD",  "TWD"),
    "HK": ("ECONOMICS:HKM2", "FX_IDC:HKDUSD",  "HKD"),
    "BR": ("ECONOMICS:BRM2", "FX_IDC:BRLUSD",  "BRL"),
    "RU": ("ECONOMICS:RUM2", "FX_IDC:RUBUSD",  "RUB"),
    "SG": ("ECONOMICS:SGM2", "FX_IDC:SGDUSD",  "SGD"),
    "SE": ("ECONOMICS:SEM2", "FX_IDC:SEKUSD",  "SEK"),
    "MX": ("ECONOMICS:MXM2", "FX_IDC:MXNUSD",  "MXN"),
    "NO": ("ECONOMICS:NOM2", "FX_IDC:NOKUSD",  "NOK"),
    "HK2":(None, None, None),  # placeholder unused
    "TH": ("ECONOMICS:THM2", "FX_IDC:THBUSD",  "THB"),
    "PH": ("ECONOMICS:PHM2", "FX_IDC:PHPUSD",  "PHP"),
    "AE": ("ECONOMICS:AEM2", "FX_IDC:AEDUSD",  "AED"),
    "MY": ("ECONOMICS:MYM2", "FX_IDC:MYRUSD",  "MYR"),
    "ID": ("ECONOMICS:IDM2", "FX_IDC:IDRUSD",  "IDR"),
    "ZA": ("ECONOMICS:ZAM2", "FX_IDC:ZARUSD",  "ZAR"),
    "SA": ("ECONOMICS:SAM2", "FX_IDC:SARUSD",  "SAR"),
    "DK": ("ECONOMICS:DKM2", "FX_IDC:DKKUSD",  "DKK"),
    "CL": ("ECONOMICS:CLM2", "FX_IDC:CLPUSD",  "CLP"),
    "IL": ("ECONOMICS:ILM2", "FX_IDC:ILSUSD",  "ILS"),
    "PL": ("ECONOMICS:PLM2", "FX_IDC:PLNUSD",  "PLN"),
    "VN": ("ECONOMICS:VNM2", "FX_IDC:VNDUSD",  "VND"),
    "CZ": ("ECONOMICS:CZM2", "FX_IDC:CZKUSD",  "CZK"),
    "TR": ("ECONOMICS:TRM2", "FX_IDC:TRYUSD",  "TRY"),
    "NG": ("ECONOMICS:NGM2", "FX_IDC:NGNUSD",  "NGN"),
    "CO": ("ECONOMICS:COM2", "FX_IDC:COPUSD",  "COP"),
    "QA": ("ECONOMICS:QAM2", "FX_IDC:QARUSD",  "QAR"),
    "HU": ("ECONOMICS:HUM2", "FX_IDC:HUFUSD",  "HUF"),
    "NZ": ("ECONOMICS:NZM2", "FX_IDC:NZDUSD",  "NZD"),
    "KW": ("ECONOMICS:KWM2", "FX_IDC:KWDUSD",  "KWD"),
    "EG": ("ECONOMICS:EGM2", "FX_IDC:EGPUSD",  "EGP"),
    "PK": ("ECONOMICS:PKM2", "FX_IDC:PKRUSD",  "PKR"),
    "KZ": ("ECONOMICS:KZM2", "FX_IDC:KZTUSD",  "KZT"),
    "UA": ("ECONOMICS:UAM2", "FX_IDC:UAHUSD",  "UAH"),
    "RO": ("ECONOMICS:ROM2", "FX_IDC:RONUSD",  "RON"),
    "BD": ("ECONOMICS:BDM2", "FX_IDC:BDTUSD",  "BDT"),
    "PE": ("ECONOMICS:PEM2", "FX_IDC:PENUSD",  "PEN"),
    "FI": ("ECONOMICS:FIM2", "FX:EURUSD",      "EUR"),
    "AR": ("ECONOMICS:ARM2", "FX_IDC:ARSUSD",  "ARS"),
}
ECON.pop("HK2", None)
